language: cpp

compiler:
    - gcc

script:
    - echo "compiling openframeworks.."

branches:
    only:
        - develop

notifications:
    email:
        recipients:
            - dias.h.bruno@gmail.com
        on_success: change
        on_failure: always
